export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
NGPUS_PER_NODE=${NGPUS_PER_NODE:-8}
n_gpus_rea=4
n_gpus_ver=$((NGPUS_PER_NODE - n_gpus_rea))


export WANDB_API_KEY='API_KEY'
WAND_PROJECT='ARR'
EXPERIMENT_NAME='qwen3-8b'
LOGFILE="logs/run_${EXPERIMENT_NAME}_$(date +%Y%m%d_%H%M%S).log"


PROJECT_DIR="$(pwd)"
DATA_DIR="${PROJECT_DIR}/data/nq_hotpotqa_train"
BASE_MODEL="PATH/TO/MODEL/Qwen3-8B"


export SGL_DISABLE_TP_MEMORY_INBALANCE_CHECK=True
export VLLM_ATTENTION_BACKEND=XFORMERS


PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
    data.train_files=$DATA_DIR/train.parquet \
    data.val_files=$DATA_DIR/test.parquet \
    data.train_batch_size=32 \
    data.val_batch_size=512 \
    data.max_prompt_length=4096 \
    data.max_response_length=1024 \
    data.max_start_length=4096 \
    data.max_obs_length=4096 \
    algorithm.adv_estimator=grpo \
    algorithm.no_think_rl=False \
    actor_rollout_ref.model.path=$BASE_MODEL \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.model.enable_activation_offload=True \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.strategy=fsdp2 \
    actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.285 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=64 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=16 \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.actor.fsdp_config.offload_policy=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.ref.log_prob_micro_batch_size=64 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=64 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.8 \
    actor_rollout_ref.rollout.n=5 \
    actor_rollout_ref.rollout.temperature=0.7 \
    actor_rollout_ref.rollout.engine_kwargs.vllm.swap_space=null \
    actor_rollout_ref.rollout.enforce_eager=True \
    actor_rollout_ref.actor.state_masking=True \
    ver_actor_rollout_ref.model.path=$BASE_MODEL \
    ver_actor_rollout_ref.model.enable_gradient_checkpointing=True \
    ver_actor_rollout_ref.model.use_remove_padding=True \
    ver_actor_rollout_ref.model.enable_activation_offload=True \
    ver_actor_rollout_ref.actor.strategy=fsdp2 \
    ver_actor_rollout_ref.actor.optim.lr=1e-6 \
    ver_actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.285 \
    ver_actor_rollout_ref.actor.use_kl_loss=True \
    ver_actor_rollout_ref.actor.ppo_mini_batch_size=64 \
    ver_actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=16 \
    ver_actor_rollout_ref.actor.fsdp_config.param_offload=True \
    ver_actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    ver_actor_rollout_ref.actor.fsdp_config.offload_policy=True \
    ver_actor_rollout_ref.actor.kl_loss_coef=0.001 \
    ver_actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    ver_actor_rollout_ref.actor.entropy_coeff=0 \
    ver_actor_rollout_ref.ref.log_prob_micro_batch_size=64 \
    ver_actor_rollout_ref.ref.fsdp_config.param_offload=True \
    ver_actor_rollout_ref.rollout.log_prob_micro_batch_size=64 \
    ver_actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    ver_actor_rollout_ref.rollout.name=vllm \
    ver_actor_rollout_ref.rollout.gpu_memory_utilization=0.8 \
    ver_actor_rollout_ref.rollout.n=5 \
    ver_actor_rollout_ref.rollout.temperature=1 \
    ver_actor_rollout_ref.rollout.engine_kwargs.vllm.swap_space=null \
    ver_actor_rollout_ref.rollout.enforce_eager=True \
    ver_actor_rollout_ref.actor.state_masking=True \
    reward_model.reward_kwargs.structure_format_score=0.0 \
    +reward_model.reward_kwargs.out_reward_type=f1\
    +reward_model.reward_kwargs.ver_clarity_beta=1.0 \
    +reward_model.reward_kwargs.adv_out_weight=1.0 \
    +reward_model.reward_kwargs.adv_ver_weight=1.0 \
    reward_model.reward_manager=adv_customed_qa \
    custom_reward_function.path=verl/utils/reward_score/rea_ver_interact_token_reward.py \
    custom_reward_function.name=compute_rea_ver_score \
    custom_val_reward_function.path=verl/utils/reward_score/rea_ver_interact_token_reward.py \
    custom_val_reward_function.name=compute_rea_ver_score \
    +reward_model.final_reward_manager=final_customed_qa \
    +custom_final_reward_function.path=verl/utils/reward_score/final_generator_reward.py \
    +custom_final_reward_function.name=compute_f1 \
    +custom_val_final_reward_function.path=verl/utils/reward_score/final_generator_reward.py \
    +custom_val_final_reward_function.name=compute_f1 \
    trainer.logger=['wandb'] \
    trainer.resume_mode=auto \
    trainer.val_only=False \
    trainer.val_before_train=True \
    trainer.default_hdfs_dir=null \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.save_freq=10 \
    trainer.test_freq=20 \
    trainer.project_name=$WAND_PROJECT \
    trainer.experiment_name=$EXPERIMENT_NAME \
    trainer.total_epochs=100 \
    trainer.total_training_steps=3000 \
    trainer.default_hdfs_dir=null \
    trainer.default_local_dir=$PROJECT_DIR/checkpoints/$EXPERIMENT_NAME \
    max_turns=5 \
    retriever.url="http://127.0.0.1:PORT/retrieve" \
    retriever.topk=3 \
    verifier.enable=True \
    data.ver_train_files=$DATA_DIR/ver_train.parquet \
    data.ver_val_files=$DATA_DIR/ver_test.parquet \
    data.validation_shuffle=False \
    trainer.rollout_data_dir=$PROJECT_DIR/rollout_data/$EXPERIMENT_NAME \
    trainer.validation_data_dir=$PROJECT_DIR/validation_data/$EXPERIMENT_NAME \
    data.dataloader_num_workers=0 \
    +data.seed=2026 \
    data.sampler.class_path=$PROJECT_DIR/verl/utils/dataset/global_index_sampler.py \
    data.sampler.class_name=GlobalIndexSampler \
    +data.val_sampler.class_path=$PROJECT_DIR/verl/utils/dataset/dist_source_index_sampler.py \
    +data.val_sampler.class_name=DistSourceIndexSampler \
    +data.val_sampler.num_samples=512 \
    trainer.n_gpus_per_node="${n_gpus_rea}" \
    ver_trainer.n_gpus_per_node="${n_gpus_ver}" \
    +data.save_detailed_rollout_data=True \
    +final_generator.enable=True \
    +final_generator.model_update=False \
    actor_rollout_ref.actor.use_dynamic_bsz=True \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=40960 \
    actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu=40960 \
    actor_rollout_ref.ref.log_prob_max_token_len_per_gpu=40960 \
    ver_actor_rollout_ref.actor.use_dynamic_bsz=True \
    ver_actor_rollout_ref.actor.ppo_max_token_len_per_gpu=40960 \
    ver_actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu=40960 \
    ver_actor_rollout_ref.ref.log_prob_max_token_len_per_gpu=40960 \
    2>&1 | tee $LOGFILE 
