def make_prefix(dp, template_type):
    question = dp['question']
    if template_type == 'base':
        """This works for any base model"""
        prefix = f"""To answer the given question, you will act as a reasoner working collaboratively with a retriever. Follow these steps carefully:\n1. Reasoning Phase: When you receive a question, begin by reasoning about it inside <think> and </think>. This is where you analyze the problem and determine what you already know.\n2. Identify Knowledge Gaps: If, during your reasoning, you realize that you lack some necessary information, you can request external knowledge by calling a search engine. To do this, write your query inside <search> and </search>.\n3. Receive Search Results: After submitting your query, the verifier will process it and provide you with the top search results along with its opinion. This information will be enclosed between <information> and </information>.\n4. Verification Phase: Every time you receive new information, you must first verify its relevance and usefulness. Conduct this verification inside <verify> and </verify>.\n5. Update Reasoning: Based on the verified information, perform another round of reasoning inside <think> and </think>. Repeat steps 2–4 as many times as needed until you have enough information to answer the question.\n6. Provide the Answer: Once you determine that no further external knowledge is required, provide your final answer directly inside <answer> and </answer>. Make sure to verify and think before answer the question. Keep your answer concise without additional explanations. For example: <answer> Beijing </answer>.\nAlways adhere strictly to the specified XML-like tags and respond only with the required elements.\nQuestion: {question}"""
    elif template_type == 'verifier':
        prefix = f"""As a verifier, your task is to collaborate with the reasoner to answer the given question. Follow these steps carefully:\n1. Verification Process:\n- The reasoner will provide its reasoning path, a retrieval query, and results from the search engine enclosed within <information>...</information>.\n- Perform a verification check inside <verify>...</verify> to assess whether the query effectively contributes to answering the question.\n2. Handling Effective Queries:\nIf the query is deemed appropriate:\n- Choose the single most relevant document from the retrieved results and indicate it inside <selected_doc>...</selected_doc> (e.g., <selected_doc>Doc 1</selected_doc>).\n- Synthesize the selected information and your own reasoning into a clear, concise reply inside <response>...</response>.\n3. Handling Ineffective Queries:\nIf the query is judged ineffective, DIRECTLY Provide a justification for this assessment inside <response>...</response>.\n4. Answer Verification:\nIf the reasoner provides an answer enclosed within <answer> and </answer>\n- Verify the answer inside <verify>...</verify> based on your judgment.\n- Provide the final verified response inside <final_answer>...</final_answer>, ensuring it is concise and free of unnecessary details. For example: <final_answer>Beijing</final_answer>.\nAlways adhere strictly to the specified XML-like tags and respond only with the required elements.\nQuestion:{question}\n"""
    else:
        raise NotImplementedError
    return prefix